#!/bin/bash

export CELERY_BROKER_URL="${REDIS_URL}"
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

sleep 5

./prepare_db

# Collect static files
echo "Collect static files"
./manage.py collectstatic --noinput

# Start server
echo "Starting server"
NOTIFICATION_WHITELIST=1 gunicorn config.wsgi -c "gunicorn_config.py" --reload --log-file -
