version: "3.1"

services:
  app: &app
    image: setlistspy_api_local
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgresql
      - redis
      - phantomjs
    links:
      - phantomjs
      - postgresql
      - redis
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "6400:6400"
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - ./compose/local/django/prepare_db:/usr/src/app/prepare_db
      - ./compose/local/django/entrypoint:/usr/src/app/entrypoint
    entrypoint: /usr/src/app/entrypoint

  postgresql:
    image: setlistspy_psql
    build:
      context: .
      dockerfile: compose/local/postgres/Dockerfile
    volumes:
      - ./database:/var/lib/postgresql
    env_file:
      - ./.envs/.local/.postgres
    expose:
      - "5432"
    labels:
      - postgresql

  redis:
    image: redis:latest
    expose:
    - "6379"

  celery-worker: &celery-worker
    image: setlistspy_api_local
    depends_on:
      - redis
      - postgresql
    links:
      - phantomjs
      - postgresql
      - redis
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - ./compose/local/django/celery/worker/start:/usr/src/app/start-celeryworker
      - ./compose/local/django/celery/beat/start:/usr/src/app/start-celerybeat
    ports: []
    command: ./start-celeryworker

  celery-beat:
    <<: *celery-worker
    command: ./start-celerybeat

  flower:
    <<: *celery-worker
    depends_on:
      - app
      - celery-worker
      - celery-beat
    command: celery flower --app=setlistspy.taskapp --broker="$REDIS_URL"
    ports:
      - "5555:5555"

  phantomjs:
    image: codeclou/docker-phantomjs-webdriver-standalone:latest
    ports:
      - "4444:4444"