# Generated by Django 2.0.8 on 2018-11-21 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('xml_md5', models.CharField(default='', max_length=32)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discogs_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('mixesdb_id', models.IntegerField()),
                ('mixesdb_mod_time', models.DateTimeField()),
                ('xml_sha1', models.CharField(max_length=31, null=True)),
                ('b2b', models.NullBooleanField(verbose_name='Other DJs on deck')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setlists', to='app.DJ')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='TrackPlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('set_order', models.IntegerField()),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='track_plays', to='app.Label')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_plays', to='app.Setlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays', to='app.Track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='setlists',
            field=models.ManyToManyField(related_name='tracks', through='app.TrackPlay', to='app.Setlist'),
        ),
        migrations.AddIndex(
            model_name='dj',
            index=models.Index(fields=['name'], name='app_dj_name_8ba7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='dj',
            index=models.Index(fields=['last_check_time'], name='app_dj_last_ch_a1f4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='dj',
            index=models.Index(fields=['name', 'last_check_time'], name='app_dj_name_51fb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackplay',
            index=models.Index(fields=['track'], name='app_trackpl_track_i_8aea96_idx'),
        ),
        migrations.AddIndex(
            model_name='trackplay',
            index=models.Index(fields=['setlist'], name='app_trackpl_setlist_37604c_idx'),
        ),
        migrations.AddIndex(
            model_name='trackplay',
            index=models.Index(fields=['track', 'setlist'], name='app_trackpl_track_i_1645eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackplay',
            unique_together={('setlist', 'set_order')},
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist'], name='app_track_artist__620f28_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['title'], name='app_track_title_935ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist', 'title'], name='app_track_artist__27c042_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('artist', 'title')},
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(fields=['dj'], name='app_setlist_dj_id_ef0f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(fields=['mixesdb_mod_time'], name='app_setlist_mixesdb_a1195a_idx'),
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(fields=['dj', 'mixesdb_mod_time'], name='app_setlist_dj_id_19887e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='setlist',
            unique_together={('dj', 'mixesdb_id')},
        ),
    ]
