# Generated by Django 2.2.1 on 2019-05-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='tracks', to='app.Artist'),
        ),
    ]
